name: Core

on: push

env:
  php: 8.2

jobs:
  PHPUnit:
    runs-on: ubuntu-22.04
    steps:
      - name: Checking out code
        uses: actions/checkout@v4
      - name: ls
        run: ls
      - name: Setting up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          ini-values: max_input_vars=5000
          tools: composer
          coverage: none
      - name: Run code
        run: php check.php
