name: Core

on: push

env:
  php: 8.2

jobs:
  PHPUnit:
    runs-on: ubuntu-22.04
    steps:
      - name: Checking out code
        uses: actions/checkout@v4
      - name: ls
        run: ls
      - name: Check systemdir
        run: php check.php
